// <auto-generated />
using System;
using FullSD_InventoryManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FullSD_InventoryManagement.Migrations
{
    [DbContext(typeof(FullSD_InventoryManagementContext))]
    [Migration("20260107073424_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FullSD_InventoryManagement.Domain.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Branch");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 7, 15, 34, 24, 61, DateTimeKind.Local).AddTicks(7057),
                            DateUpdated = new DateTime(2026, 1, 7, 15, 34, 24, 61, DateTimeKind.Local).AddTicks(7069),
                            Name = "Pasir Ris",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 7, 15, 34, 24, 61, DateTimeKind.Local).AddTicks(7071),
                            DateUpdated = new DateTime(2026, 1, 7, 15, 34, 24, 61, DateTimeKind.Local).AddTicks(7072),
                            Name = "Woodlands",
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("FullSD_InventoryManagement.Domain.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Item");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 7, 15, 34, 24, 61, DateTimeKind.Local).AddTicks(7224),
                            DateUpdated = new DateTime(2026, 1, 7, 15, 34, 24, 61, DateTimeKind.Local).AddTicks(7225),
                            Name = "Egg",
                            Quantity = 200,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 7, 15, 34, 24, 61, DateTimeKind.Local).AddTicks(7227),
                            DateUpdated = new DateTime(2026, 1, 7, 15, 34, 24, 61, DateTimeKind.Local).AddTicks(7228),
                            Name = "Vacuum Cleaner",
                            Quantity = 130,
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("FullSD_InventoryManagement.Domain.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Movement")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Order");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchID = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 7, 15, 34, 24, 61, DateTimeKind.Local).AddTicks(7441),
                            DateUpdated = new DateTime(2026, 1, 7, 15, 34, 24, 61, DateTimeKind.Local).AddTicks(7442),
                            Location = "Lot A",
                            Movement = 0,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            BranchID = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 7, 15, 34, 24, 61, DateTimeKind.Local).AddTicks(7444),
                            DateUpdated = new DateTime(2026, 1, 7, 15, 34, 24, 61, DateTimeKind.Local).AddTicks(7444),
                            Location = "Lot B",
                            Movement = 0,
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("FullSD_InventoryManagement.Domain.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderID");

                    b.ToTable("OrderDetail");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 7, 15, 34, 24, 61, DateTimeKind.Local).AddTicks(7359),
                            DateUpdated = new DateTime(2026, 1, 7, 15, 34, 24, 61, DateTimeKind.Local).AddTicks(7360),
                            ItemID = 1,
                            OrderID = 1,
                            Quantity = 50,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 7, 15, 34, 24, 61, DateTimeKind.Local).AddTicks(7362),
                            DateUpdated = new DateTime(2026, 1, 7, 15, 34, 24, 61, DateTimeKind.Local).AddTicks(7363),
                            ItemID = 2,
                            OrderID = 1,
                            Quantity = 20,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 7, 15, 34, 24, 61, DateTimeKind.Local).AddTicks(7365),
                            DateUpdated = new DateTime(2026, 1, 7, 15, 34, 24, 61, DateTimeKind.Local).AddTicks(7365),
                            ItemID = 1,
                            OrderID = 2,
                            Quantity = 10,
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("FullSD_InventoryManagement.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("FullSD_InventoryManagement.Domain.OrderDetail", b =>
                {
                    b.HasOne("FullSD_InventoryManagement.Domain.Order", null)
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FullSD_InventoryManagement.Domain.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
